spring:
  cloud:
    stream:
      bindings:
        order_to_mall_01:
          group: demo_stream_mall_1
          destination: demo.order_to_mall_01
          content-type: application/json
        purchase_to_mall_01:
          group: demo_stream_mall_1
          destination: demo.purchase_to_mall_01
          content-type: application/json
server:
  port: 8862