spring:
  application:
    name: DEMO-STREAM-MALL
  rabbitmq:
    addresses: 192.168.199.113:5672,192.168.199.114:5672
    username: demo
    password: 1990912
    virtual-host: demo
    connection-timeout: 60000
  cloud:
    stream:
      bindings:
        order_to_mall_01:
          group: demo_stream_mall
          destination: demo.order_to_mall_01
          content-type: application/json
        purchase_to_mall_01:
          group: demo_stream_mall
          destination: demo.purchase_to_mall_01
          content-type: application/json
server:
  servlet:
    context-path: /demo