zuul:
  add-host-header: true
  routes:
    demoone:
      path: /demoone/**
      serviceId: DEMOONE
    demo-feign:
      path: /demo-feign/**
      url: http://localhost:8361/demo/
  retryable: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
app:
  from: local-file-1.0