spring:
  application:
    name: demo-zuul
server:
  port: 8261
  servlet:
    context-path: /demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/demo/eureka/,http://peer2:8762/demo/eureka/
zuul:
  routes:
    demoone:
      path: /demoone/demo/**
      serviceId: DEMOONE
    demo-feign:
      path: /demo-feign/demo/**
      serviceId: DEMO-FEIGN