spring:
  application:
    rabbitmq:
      addresses: 192.168.199.113:5672,192.168.199.114:5672
      username: demo
      password: 1990912
      virtual-host: demo
      connection-timeout: 60000
server:
  port: 7261
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  add-host-header: true
  routes:
    demoone:
      path: /demoone/**
      serviceId: DEMOONE
    demo-feign:
      path: /demo-feign/**
      url: http://localhost:8361/demo/
  retryable: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
app:
  from: demo-zul-git-6.0