spring:
  application:
    name: DEMO-ZUUL
server:
  port: 7261
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/demo/eureka/,http://peer2:8762/demo/eureka/
zuul:
  add-host-header: true
  routes:
    demoone:
      path: /demoone/**
      serviceId: DEMOONE
    demo-feign:
      path: /demo-feign/**
      serviceId: DEMO-FEIGN
  retryable: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
app:
  from: git-dev-3.0