spring:
  application:
    name: demo-turbine
  banner:
    charset: UTF-8
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8461
  servlet:
    context-path: /demo
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/demo/eureka/,http://peer2:8762/demo/eureka/
turbine:
  app-config: demo-ribbon
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix: demo/actuator/hystrix.stream