spring:
  application:
    name: demoone-v1
  banner:
    charset: UTF-8
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/demo/eureka/,http://peer2:8762/demo/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  servlet:
    context-path: /demo
  tomcat:
    uri-encoding: UTF-8
