spring:
  application:
    name: demo-turbine-amqp
  banner:
    charset: UTF-8
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  rabbitmq:
    addresses: 192.168.199.113:5672,192.168.199.114:5672
    username: demo
    password: 1990912
    virtual-host: demo
    connection-timeout: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/demo/eureka/,http://peer2:8762/demo/eureka/
  instance:
    non-secure-port: 8389
turbine:
  app-config: demo-ribbon
  port: 8389
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix: demo/actuator/hystrix.stream