spring:
  application:
    name: DEMO-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangqiang110/demo-spring-cloud.git
          search-paths:
          - demo-config-repo
          username: momogoing@163.com
          password: xiaoqiang2008
        encrypt:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/demo/eureka/,http://peer2:8762/demo/eureka/